version: "3.3"
services:
  redis:
    image: redis:4-alpine
    volumes:
      - type: bind
        source: ./redis-data
        target: /data
    command:
      - redis-server
      - --requirepass
      - admin
    ports:
      - 127.0.0.1:6379:6379